service: ch-sls-tutorial
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000  

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  environment:
    variable1: value1
  httpApi:
    cors: true

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

functions:
  create:
    handler: src/handler.create
    events:
      - httpApi:
          path: /tutorial/user/create
          method: post
  update:
    handler: src/handler.update
    events:
      - httpApi:
          path: /tutorial/user/update
          method: post
  delete:
    handler: src/handler.delete
    events:
      - httpApi:
          path: /tutorial/user/delete
          method: post
  all:
    handler: src/handler.all
    events:
      - httpApi:
          path: /tutorial/user/all
          method: post
  getUserById:
    handler: src/handler.getUserById
    events:
      - httpApi:
          path: /tutorial/user/getUserById
          method: post                    
