service: ch-sls-tutorial
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000  

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  environment:
    variable1: value1
  httpApi:
    cors: true

package:
  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello/good-day
          method: post
